# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'FSPagerView'
  # Pods for ExampleViewController

  target 'ExampleViewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleViewControllerUITests' do
    # Pods for testing
  end

end
